// Copyright (c) Fensak, LLC.
// SPDX-License-Identifier: MPL-2.0
//
// -----             IMPORTANT             ------
// ----- DO NOT MODIFY THIS FILE BY HAND!! ------
// This file is autogenerated by senc-libgenerator.

import validateGitHubActionsWorkflowConfig from "./validator.mjs";
export { validateGitHubActionsWorkflowConfig };
